### ISSUE TITLE
AWS EC2 인스턴스에 docker-compose 를 이용해 배포시 ERROR: Couldn't connect to Docker daemon

### ISSUE THREAD

**Issue by hunao3o** [92-crew/dod-api#24]
docker 를 이용하여 mysql 배포

*docker-compose.yml*
```
services:
  db:
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=adminadmin
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mysql-test:/var/lib/mysql
```

`$ docker-compose up -d`

error caused
`ERROR: Couldn't connect to Docker daemon - you might need to run 'docker-machine start default'.`
